name: unifyfreelancer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  get: ^4.6.5
  flutter_screenutil: ^5.6.0
#  flutter_launcher_icons: ^0.11.0
  form_field_validator: ^1.1.0
#  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.6
  file_picker:
  path_provider: ^2.0.11
#  country_pickers:
#  country_calling_code_picker: ^2.0.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_otp_text_field: ^1.1.1
  syncfusion_flutter_datepicker: ^20.3.58
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6
  flutter_spinkit: ^5.1.0
  firebase_core:
  firebase_auth:
  google_sign_in:
  cloud_firestore: ^4.1.0
  cached_network_image:
  another_stepper: ^1.1.6
  loading_animation_widget: ^1.2.0+3
  url_launcher: ^6.1.7
  flutter_stripe: ^7.0.0
  pin_code_fields:
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/unifyIcon.png"
#  min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
